spring.main.allow-bean-definition-overriding: true

server.port: 9000
management.port: 9001

spring:
    security:
        oauth2:
            client:
                provider:
                    mocklab:
                        authorization-uri: https://oauth.mocklab.io/oauth/authorize
                        token-uri: https://oauth.mocklab.io/oauth/token
                        user-info-uri: https://oauth.mocklab.io/userinfo
                        user-name-attribute: sub
                        jwk-set-uri: https://oauth.mocklab.io/.well-known/jwks.json

                registration:
                    mock-oauth2:
                        provider: mocklab
                        authorization-grant-type: authorization_code
                        scope: email
                        redirect-uri: "{baseUrl}/{action}/oauth2/code/{registrationId}"
                        clientId: mocklab_oauth2
                        clientSecret: whatever

                    mock-oidc:
                        provider: mocklab
                        authorization-grant-type: authorization_code
                        scope: openid, profile, email
                        redirect-uri: "{baseUrl}/{action}/oauth2/code/{registrationId}"
                        clientId: mocklab_oidc
                        clientSecret: whatever

spring.mustache.expose-request-attributes: true

mockapi.baseurl: http://live-demo.mocklab.io
backend.http.read-timeout: 30000

paypal.endpoint: https://paypal-demo.mocklab.io/
#paypal.endpoint: https://api.sandbox.paypal.com/

paypal.client.id: AX7GYdURLc6DOP8d4FZmC8Chduox_EdfVmn_OsoAcgc-FrnrSYD2EFHZebApvq5yQszXc4NhzdXunAD4
paypal.client.secret: xxx

logging:
    level:
        org:
            springframework: DEBUG